[project]
name = "contract"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"


[contracts.Factory_v7]
path = "contracts/Factory.clar"

[contracts.KeyVendingMachine_v7]
path = "contracts/KeyVendingMachine.clar"

[contracts.KeyToken_v7]
path = "contracts/KeyToken.clar"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
